-- SAIKO Construction AI v12 — multi-data detection + storage patch
-- Safe add-on: preserves existing data.

grant usage on schema public to authenticated;

create table if not exists public.variation_orders (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade,
  vo_no text,
  description text,
  amount numeric default 0,
  status text default 'Imported',
  source_file text,
  created_by uuid,
  created_at timestamptz default now()
);

grant select, insert, update, delete on public.variation_orders to authenticated;
alter table public.variation_orders enable row level security;
drop policy if exists variation_orders_all_authenticated on public.variation_orders;
create policy variation_orders_all_authenticated on public.variation_orders for all to authenticated using (true) with check (true);

alter table public.project_files add column if not exists detected_modules text;
alter table public.project_files add column if not exists detected_summary text;
grant select, insert, update, delete on public.project_files to authenticated;

insert into storage.buckets (id,name,public)
values ('project-files','project-files',false)
on conflict (id) do update set public=false;

insert into storage.buckets (id,name,public)
values ('templates','templates',false)
on conflict (id) do update set public=false;

drop policy if exists saiko_storage_select on storage.objects;
drop policy if exists saiko_storage_insert on storage.objects;
drop policy if exists saiko_storage_update on storage.objects;
drop policy if exists saiko_storage_delete on storage.objects;
create policy saiko_storage_select on storage.objects for select to authenticated using (bucket_id in ('project-files','templates'));
create policy saiko_storage_insert on storage.objects for insert to authenticated with check (bucket_id in ('project-files','templates'));
create policy saiko_storage_update on storage.objects for update to authenticated using (bucket_id in ('project-files','templates')) with check (bucket_id in ('project-files','templates'));
create policy saiko_storage_delete on storage.objects for delete to authenticated using (bucket_id in ('project-files','templates'));

select 'v12 multi-data + storage patch complete' as result;
