-- SAIKO Construction AI v14.8
-- Multi-user presence, safe record locks, activity log, and row history.

create table if not exists public.collaboration_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  module text,
  project_id uuid references public.projects(id) on delete set null,
  last_seen timestamptz not null default now()
);

create table if not exists public.collaboration_locks (
  module text not null,
  record_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text,
  project_id uuid references public.projects(id) on delete set null,
  locked_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 minutes'),
  primary key (module, record_id)
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  display_name text,
  module text not null,
  action text not null,
  record_id text,
  project_id uuid references public.projects(id) on delete set null,
  description text,
  change_data jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.record_history (
  id bigint generated by default as identity primary key,
  module text not null,
  record_id text not null,
  project_id uuid references public.projects(id) on delete set null,
  changed_by uuid references auth.users(id) on delete set null,
  display_name text,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_collab_presence_seen on public.collaboration_presence(last_seen desc);
create index if not exists idx_collab_locks_expires on public.collaboration_locks(expires_at);
create index if not exists idx_activity_log_created on public.activity_log(created_at desc);
create index if not exists idx_activity_log_project on public.activity_log(project_id, created_at desc);
create index if not exists idx_record_history_record on public.record_history(module, record_id, created_at desc);

alter table public.collaboration_presence enable row level security;
alter table public.collaboration_locks enable row level security;
alter table public.activity_log enable row level security;
alter table public.record_history enable row level security;

grant select, insert, update, delete on public.collaboration_presence to authenticated;
grant select, insert, update, delete on public.collaboration_locks to authenticated;
grant select, insert on public.activity_log to authenticated;
grant select, insert on public.record_history to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists collaboration_presence_read on public.collaboration_presence;
create policy collaboration_presence_read on public.collaboration_presence
for select to authenticated using (true);

drop policy if exists collaboration_presence_own_write on public.collaboration_presence;
create policy collaboration_presence_own_write on public.collaboration_presence
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists collaboration_locks_read on public.collaboration_locks;
create policy collaboration_locks_read on public.collaboration_locks
for select to authenticated using (true);

drop policy if exists collaboration_locks_own_delete on public.collaboration_locks;
create policy collaboration_locks_own_delete on public.collaboration_locks
for delete to authenticated using (auth.uid() = user_id);

drop policy if exists activity_log_read on public.activity_log;
create policy activity_log_read on public.activity_log
for select to authenticated using (true);

drop policy if exists activity_log_insert_own on public.activity_log;
create policy activity_log_insert_own on public.activity_log
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists record_history_read on public.record_history;
create policy record_history_read on public.record_history
for select to authenticated using (true);

drop policy if exists record_history_insert_own on public.record_history;
create policy record_history_insert_own on public.record_history
for insert to authenticated with check (auth.uid() = changed_by);

-- Atomic lock acquisition. Expired locks can be taken over.
create or replace function public.acquire_record_lock(
  p_module text,
  p_record_id text,
  p_display_name text default null,
  p_project_id uuid default null
)
returns table(acquired boolean, owner_user_id uuid, owner_name text, expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_lock public.collaboration_locks%rowtype;
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  delete from public.collaboration_locks
  where expires_at < now();

  insert into public.collaboration_locks(module, record_id, user_id, display_name, project_id, locked_at, expires_at)
  values(p_module, p_record_id, v_uid, p_display_name, p_project_id, now(), now() + interval '2 minutes')
  on conflict (module, record_id) do update
    set user_id = excluded.user_id,
        display_name = excluded.display_name,
        project_id = excluded.project_id,
        locked_at = now(),
        expires_at = now() + interval '2 minutes'
    where public.collaboration_locks.user_id = v_uid
       or public.collaboration_locks.expires_at < now();

  select * into v_lock
  from public.collaboration_locks
  where module=p_module and record_id=p_record_id;

  return query
  select (v_lock.user_id = v_uid), v_lock.user_id, v_lock.display_name, v_lock.expires_at;
end;
$$;

create or replace function public.release_record_lock(p_module text, p_record_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.collaboration_locks
  where module=p_module and record_id=p_record_id and user_id=auth.uid();
  return found;
end;
$$;

grant execute on function public.acquire_record_lock(text,text,text,uuid) to authenticated;
grant execute on function public.release_record_lock(text,text) to authenticated;

select 'SAIKO Construction AI v14.8 collaboration layer ready' as result;
