// SAIKO Construction AI v21.3 — editable Summary mirror
(function(){
  const $=id=>document.getElementById(id); let editing=false;
  function selectedQuotation(){const list=cache.quotationProjects||[];const active=document.querySelector('.quotation-project-card.active');const id=active?.dataset?.quotationId;return id?list.find(q=>String(q.id)===String(id))||null:list[0]||null}
  function arr(v){if(Array.isArray(v))return v;if(typeof v==='string'){try{const x=JSON.parse(v);return Array.isArray(x)?x:[]}catch(_){}}return []}
  function clone(v){return JSON.parse(JSON.stringify(v??null))}
  function parseNumber(text){const s=String(text??'').replace(/[₱,$,%\s]/g,'').replace(/,/g,'');if(!s||!/^[-+]?\d*\.?\d+$/.test(s))return null;const n=Number(s);return Number.isFinite(n)?n:null}
  function setButtons(){$('editSummaryDataBtn')?.classList.toggle('hidden',editing);$('saveSummaryDataBtn')?.classList.toggle('hidden',!editing);$('cancelSummaryDataBtn')?.classList.toggle('hidden',!editing)}
  function setEditable(on){const table=$('quotationSummaryMirrorTable');if(!table)return;table.classList.toggle('is-editing',on);table.querySelectorAll('tbody td[title]').forEach(td=>{const address=(td.getAttribute('title')||'').trim();if(!address)return;td.contentEditable=on?'true':'false';td.spellcheck=false;td.classList.toggle('editable-summary-cell',on)})}
  function beginEdit(){const q=selectedQuotation();if(!q||!arr(q.summary_table).length){if(typeof toast==='function')toast('Refresh from Sheet first so Summary data is available.');return}editing=true;setButtons();setEditable(true);if(typeof toast==='function')toast('Summary data is now editable.')}
  function cancelEdit(){editing=false;setButtons();setEditable(false);if(typeof window.renderQuotationSummaryMirror==='function')window.renderQuotationSummaryMirror()}
  function readEditedTable(q){const original=clone(arr(q.summary_table)),map=new Map();for(const row of original)for(const cell of row.cells||[])map.set(String(cell.address||''),cell);$('quotationSummaryMirrorTable')?.querySelectorAll('tbody td[title]').forEach(td=>{const address=(td.getAttribute('title')||'').trim(),cell=map.get(address);if(!cell)return;const display=td.textContent.trim(),num=parseNumber(display);cell.display=display;cell.numeric=num;if(cell.isPercent)cell.percentage=num});return original}
  function syncBreakdown(q,table){const cellMap=new Map();for(const row of table)for(const cell of row.cells||[])cellMap.set(String(cell.address||''),cell);const breakdown=clone(arr(q.summary_breakdown));for(const cat of breakdown){if(cat.amountCell&&cellMap.has(String(cat.amountCell))){const c=cellMap.get(String(cat.amountCell));if(Number.isFinite(c.numeric))cat.amount=c.numeric}if(cat.percentCell&&cellMap.has(String(cat.percentCell))){const c=cellMap.get(String(cat.percentCell)),n=Number.isFinite(c.percentage)?c.percentage:c.numeric;if(Number.isFinite(n))cat.percentage=n}for(const item of cat.items||[]){if(item.amountCell&&cellMap.has(String(item.amountCell))){const c=cellMap.get(String(item.amountCell));if(Number.isFinite(c.numeric))item.amount=c.numeric}if(item.percentCell&&cellMap.has(String(item.percentCell))){const c=cellMap.get(String(item.percentCell)),n=Number.isFinite(c.percentage)?c.percentage:c.numeric;if(Number.isFinite(n))item.percentage=n}}}const scope=breakdown.map(c=>({name:c.name,amount:Number(c.amount||0),percentage:Number(c.percentage||0),source:c.source||null}));return{breakdown,scope}}
  async function saveEdit(){if(!editing)return;const q=selectedQuotation();if(!q)return;const btn=$('saveSummaryDataBtn');if(btn){btn.disabled=true;btn.textContent='Saving…'}try{const summary_table=readEditedTable(q),synced=syncBreakdown(q,summary_table);const {error}=await sb.from('quotation_projects').update({summary_table,summary_breakdown:synced.breakdown,scope_breakdown:synced.scope,updated_at:new Date().toISOString()}).eq('id',q.id);if(error)throw error;try{await sb.from('activity_log').insert({project_id:null,module:'quotation',record_id:String(q.id),action:'summary_manual_edit',details:{project_name:q.project_name,edited_summary_data:true},created_by:currentUser.id})}catch(_){}editing=false;setButtons();setEditable(false);await refreshAll();if(typeof window.renderQuotationSummaryMirror==='function')window.renderQuotationSummaryMirror();if(typeof window.renderQuotationSummary==='function')window.renderQuotationSummary();if(typeof renderPending==='function')renderPending();if(typeof toast==='function')toast('Summary data saved.')}catch(err){alert('Save failed: '+(err?.message||err))}finally{if(btn){btn.disabled=false;btn.textContent='Save'}}}
  $('editSummaryDataBtn')?.addEventListener('click',beginEdit);$('saveSummaryDataBtn')?.addEventListener('click',saveEdit);$('cancelSummaryDataBtn')?.addEventListener('click',cancelEdit);
  document.addEventListener('click',e=>{if(editing&&e.target.closest?.('.quotation-project-card[data-quotation-id]')){editing=false;setButtons();setTimeout(()=>setEditable(false),0)}},{passive:true});setButtons();
})();
